package gamedata

// Code generated from the client locale (resources.assets IDS_Quest_Map_4_* entries)
// by scratchpad/gen_quests.py. DO NOT EDIT BY HAND -- regenerate instead.
//
// One row per baked PvE story quest. Key is the locale infix: the client resolves
// IDS_Quest_<Key>_<Name|JournalDesc|DialogBegin|DialogProgress|DialogEnd|GuiProgress>
// to display text -- the server only ever cites these keys, never invents text.
// MapID is the Hunt map the quest is fought on (40/41/42); Count is parsed from the
// journal text; Kind is QuestType (1 KILL, 2 COLLECT); PveType is QuestPvEType
// (1 SINGLE, 2 GROUP, 3 REPLAY). The *Key fields are pre-resolved to locale keys
// whose baked value is non-empty (fallback to JournalDesc/Name), so the client
// never renders "EMPTY!".
type questDef struct {
	Key      string // stable identity infix (IDS_Quest_<Key>_...)
	MapID    int32
	PveType  int32
	Kind     int32
	Count    int32
	NameKey  string // quest title
	TaskKey  string // task_desc (journal one-liner)
	StartKey string // start_desc (NPC dialog before accept)
	ProgKey  string // in_progress_desc (NPC dialog while active)
	WinKey   string // win_desc (NPC dialog when ready to turn in)
	GuiKey   string // progress-bar label
}

var questDefs = []questDef{
	{Key: "NPC1_PVE_Single_Stage1_1", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage1_1_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage1_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage1_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage1_3", MapID: 40, PveType: 1, Kind: 1, Count: 10, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage1_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage1_4", MapID: 40, PveType: 1, Kind: 1, Count: 20, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage1_4_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage2_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage2_1_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage2_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage2_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage2_3", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage2_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage2_4", MapID: 40, PveType: 1, Kind: 1, Count: 25, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage2_4_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage2_5", MapID: 40, PveType: 1, Kind: 2, Count: 10, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage2_5_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage3_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage3_1_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage3_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage3_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage3_3", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage3_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage3_4", MapID: 40, PveType: 1, Kind: 2, Count: 20, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage3_4_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage3_5", MapID: 40, PveType: 1, Kind: 2, Count: 16, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage3_5_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage4_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage4_1_JournalDesc"},
	{Key: "NPC1_PVE_Single_Stage4_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage4_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage4_3", MapID: 40, PveType: 1, Kind: 1, Count: 20, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage4_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage4_4", MapID: 40, PveType: 1, Kind: 2, Count: 15, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage4_4_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage5_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage5_1_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage5_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage5_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage5_3", MapID: 40, PveType: 1, Kind: 1, Count: 25, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage5_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage5_4", MapID: 40, PveType: 1, Kind: 2, Count: 15, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage5_4_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage6_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage6_1_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage6_2", MapID: 40, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage6_2_JournalDesc"},
	{Key: "NPC1_PVE_Single_Stage6_3", MapID: 40, PveType: 1, Kind: 1, Count: 200, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage6_3_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage7_1", MapID: 40, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage7_1_JournalDesc"},
	{Key: "NPC1_PVE_Single_Stage7_2", MapID: 40, PveType: 1, Kind: 1, Count: 50, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage7_2_GuiProgress"},
	{Key: "NPC1_PVE_Single_Stage7_3", MapID: 40, PveType: 1, Kind: 2, Count: 30, NameKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_Name", TaskKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_JournalDesc", StartKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_DialogBegin", ProgKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_DialogProgress", WinKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_DialogEnd", GuiKey: "IDS_Quest_NPC1_PVE_Single_Stage7_3_GuiProgress"},
	{Key: "Map_4_0_NPC1_PVE_Repeat_Stage8_1", MapID: 40, PveType: 3, Kind: 1, Count: 20, NameKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_Name", TaskKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_JournalDesc", StartKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_DialogProgress", WinKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_1_GuiProgress"},
	{Key: "Map_4_0_NPC1_PVE_Repeat_Stage8_2", MapID: 40, PveType: 3, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_Name", TaskKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_JournalDesc", StartKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_DialogProgress", WinKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_0_NPC1_PVE_Repeat_Stage8_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_DropStage_1", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_JournalDesc", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_JournalDesc", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_1_JournalDesc"},
	{Key: "Map_4_1_NPC1_PVE_Group_DropStage_2", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_DropStage_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_1", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_1_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_2", MapID: 41, PveType: 2, Kind: 1, Count: 3, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_3", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_3_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_4", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_4_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_5", MapID: 41, PveType: 2, Kind: 1, Count: 10, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_5_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_6", MapID: 41, PveType: 2, Kind: 2, Count: 12, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_6_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_7", MapID: 41, PveType: 2, Kind: 1, Count: 8, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_7_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_8", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_8_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage1_9", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage1_9_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_1", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_1_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_2", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_3", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_3_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_4", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_4_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_5", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_5_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_6", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_6_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_7", MapID: 41, PveType: 2, Kind: 2, Count: 8, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_7_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_8", MapID: 41, PveType: 2, Kind: 2, Count: 12, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_8_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage2_9", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage2_9_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_1", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_1_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_2", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_3", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_3_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_4", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_4_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_5", MapID: 41, PveType: 2, Kind: 1, Count: 15, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_5_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_6", MapID: 41, PveType: 2, Kind: 1, Count: 16, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_6_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage3_7", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage3_7_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage4_1", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_1_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage4_2", MapID: 41, PveType: 2, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_2_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage4_3", MapID: 41, PveType: 2, Kind: 2, Count: 12, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_3_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage4_4", MapID: 41, PveType: 2, Kind: 1, Count: 50, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_4_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Group_Stage4_5", MapID: 41, PveType: 2, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Group_Stage4_5_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Repeat_Stage5_1", MapID: 41, PveType: 3, Kind: 2, Count: 18, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_1_GuiProgress"},
	{Key: "Map_4_1_NPC1_PVE_Repeat_Stage5_2", MapID: 41, PveType: 3, Kind: 1, Count: 25, NameKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_Name", TaskKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_JournalDesc", StartKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_DialogProgress", WinKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_1_NPC1_PVE_Repeat_Stage5_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_1", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_1_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_2", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_3", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_3_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_4", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_4_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_5", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_5_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_6", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_6_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_7", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_7_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_8", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_8_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_9", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_9_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_10", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_10_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_11", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_11_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_12", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_12_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_13", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_13_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_14", MapID: 42, PveType: 1, Kind: 1, Count: 20, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_14_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_15", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_15_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage1_16", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage1_16_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_1", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_1_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_2", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_3", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_3_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_4", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_4_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_5", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_5_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage2_6", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage2_6_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_1", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_1_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_2", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_3", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_3_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_4", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_4_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_5", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_5_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_6", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_6_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage3_7", MapID: 42, PveType: 1, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage3_7_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage4_1", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_1_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage4_2", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage4_3", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_3_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage4_4", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_4_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Single_Stage4_5", MapID: 42, PveType: 1, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Single_Stage4_5_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Repeat_Stage5_1", MapID: 42, PveType: 3, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_1_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Repeat_Stage5_2", MapID: 42, PveType: 3, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_2_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Repeat_Stage5_3", MapID: 42, PveType: 3, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_3_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Repeat_Stage5_4", MapID: 42, PveType: 3, Kind: 2, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_4_GuiProgress"},
	{Key: "Map_4_2_NPC1_PVE_Repeat_Stage5_5", MapID: 42, PveType: 3, Kind: 1, Count: 1, NameKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_Name", TaskKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_JournalDesc", StartKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_DialogBegin", ProgKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_DialogProgress", WinKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_DialogEnd", GuiKey: "IDS_Quest_Map_4_2_NPC1_PVE_Repeat_Stage5_5_GuiProgress"},
}
