// Code generated from the client's baked Set-item locale + icon manifest. DO NOT EDIT the
// table by hand: it is a 1:1 transcription of the 348 IDS_Set_* wearables the client ships
// (regenerate from the locale, never invent). Stat VALUES are authored in wearable_items.go.

package gamedata

// setItemDef is one baked "Set" wearable, keyed by its locale coordinates
// (IDS_Set_<Race>_S<Tier>_<Color>_<Slot>). Icon is the container key relative to
// "Gui/Icons/Items/" (the client prepends that): the 22 per-race missing textures
// (S5 Violet + S3/S4/S5 Blue Weapon) fall back to same-slot art, since rarity is a frame
// overlay. Stats are the stat-name placeholders in the item's baked LongDesc.
type setItemDef struct {
	Race  string
	Tier  int32
	Color string
	Slot  string
	Level int32
	Icon  string
	Stats []string
}

var setItemDefs = []setItemDef{
	{"Elf", 0, "Grey", "Belt", 1, "elf/set/set_elf_s0_grey_belt", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 0, "Grey", "Foots", 5, "elf/set/set_elf_s0_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 0, "Grey", "Hands", 7, "elf/set/set_elf_s0_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 0, "Grey", "Legs", 1, "elf/set/set_elf_s0_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 0, "Grey", "Shoulders", 4, "elf/set/set_elf_s0_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 0, "Grey", "Weapon", 8, "elf/set/set_elf_s0_grey_weapon", []string{"DamageMin"}},
	{"Elf", 1, "Grey", "Belt", 15, "elf/set/set_elf_s1_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 1, "Grey", "Body", 11, "elf/set/set_elf_s1_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 1, "Grey", "Foots", 14, "elf/set/set_elf_s1_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 1, "Grey", "Hands", 16, "elf/set/set_elf_s1_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 1, "Grey", "Helm", 17, "elf/set/set_elf_s1_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 1, "Grey", "Legs", 12, "elf/set/set_elf_s1_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 1, "Grey", "Shoulders", 13, "elf/set/set_elf_s1_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 1, "Grey", "Weapon", 18, "elf/set/set_elf_s1_grey_weapon", []string{"DamageMin"}},
	{"Elf", 1, "Green", "Belt", 15, "elf/set/set_elf_s1_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 1, "Green", "Body", 11, "elf/set/set_elf_s1_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 1, "Green", "Foots", 14, "elf/set/set_elf_s1_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 1, "Green", "Hands", 16, "elf/set/set_elf_s1_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 1, "Green", "Helm", 17, "elf/set/set_elf_s1_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 1, "Green", "Legs", 12, "elf/set/set_elf_s1_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 1, "Green", "Shoulders", 13, "elf/set/set_elf_s1_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 1, "Green", "Weapon", 18, "elf/set/set_elf_s1_green_weapon", []string{"DamageMin"}},
	{"Elf", 2, "Grey", "Belt", 25, "elf/set/set_elf_s2_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 2, "Grey", "Body", 21, "elf/set/set_elf_s2_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 2, "Grey", "Foots", 24, "elf/set/set_elf_s2_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 2, "Grey", "Hands", 26, "elf/set/set_elf_s2_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 2, "Grey", "Helm", 27, "elf/set/set_elf_s2_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 2, "Grey", "Legs", 22, "elf/set/set_elf_s2_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 2, "Grey", "Shoulders", 23, "elf/set/set_elf_s2_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 2, "Grey", "Weapon", 28, "elf/set/set_elf_s2_grey_weapon", []string{"DamageMin"}},
	{"Elf", 2, "Green", "Belt", 25, "elf/set/set_elf_s2_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 2, "Green", "Body", 21, "elf/set/set_elf_s2_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 2, "Green", "Foots", 24, "elf/set/set_elf_s2_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 2, "Green", "Hands", 26, "elf/set/set_elf_s2_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 2, "Green", "Helm", 27, "elf/set/set_elf_s2_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 2, "Green", "Legs", 22, "elf/set/set_elf_s2_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 2, "Green", "Shoulders", 23, "elf/set/set_elf_s2_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 2, "Green", "Weapon", 28, "elf/set/set_elf_s2_green_weapon", []string{"DamageMin"}},
	{"Elf", 3, "Grey", "Belt", 35, "elf/set/set_elf_s3_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 3, "Grey", "Body", 31, "elf/set/set_elf_s3_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Grey", "Foots", 34, "elf/set/set_elf_s3_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Grey", "Hands", 36, "elf/set/set_elf_s3_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 3, "Grey", "Helm", 37, "elf/set/set_elf_s3_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 3, "Grey", "Legs", 32, "elf/set/set_elf_s3_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 3, "Grey", "Shoulders", 33, "elf/set/set_elf_s3_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 3, "Grey", "Weapon", 38, "elf/set/set_elf_s3_grey_weapon", []string{"DamageMin"}},
	{"Elf", 3, "Green", "Belt", 35, "elf/set/set_elf_s3_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 3, "Green", "Body", 31, "elf/set/set_elf_s3_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Green", "Foots", 34, "elf/set/set_elf_s3_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Green", "Hands", 36, "elf/set/set_elf_s3_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 3, "Green", "Helm", 37, "elf/set/set_elf_s3_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 3, "Green", "Legs", 32, "elf/set/set_elf_s3_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 3, "Green", "Shoulders", 33, "elf/set/set_elf_s3_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 3, "Green", "Weapon", 38, "elf/set/set_elf_s3_green_weapon", []string{"DamageMin"}},
	{"Elf", 3, "Blue", "Belt", 35, "elf/set/set_elf_s3_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 3, "Blue", "Body", 31, "elf/set/set_elf_s3_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Blue", "Foots", 34, "elf/set/set_elf_s3_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 3, "Blue", "Hands", 36, "elf/set/set_elf_s3_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 3, "Blue", "Helm", 37, "elf/set/set_elf_s3_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 3, "Blue", "Legs", 32, "elf/set/set_elf_s3_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 3, "Blue", "Shoulders", 33, "elf/set/set_elf_s3_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 3, "Blue", "Weapon", 38, "elf/set/set_elf_s3_grey_weapon", []string{"DamageMin"}},
	{"Elf", 4, "Grey", "Belt", 45, "elf/set/set_elf_s4_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 4, "Grey", "Body", 41, "elf/set/set_elf_s4_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Grey", "Foots", 44, "elf/set/set_elf_s4_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Grey", "Hands", 46, "elf/set/set_elf_s4_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 4, "Grey", "Helm", 47, "elf/set/set_elf_s4_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 4, "Grey", "Legs", 42, "elf/set/set_elf_s4_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 4, "Grey", "Shoulders", 43, "elf/set/set_elf_s4_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 4, "Grey", "Weapon", 48, "elf/set/set_elf_s4_grey_weapon", []string{"DamageMin"}},
	{"Elf", 4, "Green", "Belt", 45, "elf/set/set_elf_s4_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 4, "Green", "Body", 41, "elf/set/set_elf_s4_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Green", "Foots", 44, "elf/set/set_elf_s4_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Green", "Hands", 46, "elf/set/set_elf_s4_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 4, "Green", "Helm", 47, "elf/set/set_elf_s4_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 4, "Green", "Legs", 42, "elf/set/set_elf_s4_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 4, "Green", "Shoulders", 43, "elf/set/set_elf_s4_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 4, "Green", "Weapon", 48, "elf/set/set_elf_s4_green_weapon", []string{"DamageMin"}},
	{"Elf", 4, "Blue", "Belt", 45, "elf/set/set_elf_s4_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 4, "Blue", "Body", 41, "elf/set/set_elf_s4_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Blue", "Foots", 44, "elf/set/set_elf_s4_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 4, "Blue", "Hands", 46, "elf/set/set_elf_s4_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 4, "Blue", "Helm", 47, "elf/set/set_elf_s4_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 4, "Blue", "Legs", 42, "elf/set/set_elf_s4_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 4, "Blue", "Shoulders", 43, "elf/set/set_elf_s4_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 4, "Blue", "Weapon", 48, "elf/set/set_elf_s4_grey_weapon", []string{"DamageMin"}},
	{"Elf", 5, "Grey", "Belt", 55, "elf/set/set_elf_s5_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 5, "Grey", "Body", 51, "elf/set/set_elf_s5_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Grey", "Foots", 54, "elf/set/set_elf_s5_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Grey", "Hands", 56, "elf/set/set_elf_s5_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 5, "Grey", "Helm", 57, "elf/set/set_elf_s5_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 5, "Grey", "Legs", 52, "elf/set/set_elf_s5_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 5, "Grey", "Shoulders", 53, "elf/set/set_elf_s5_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 5, "Grey", "Weapon", 58, "elf/set/set_elf_s5_grey_weapon", []string{"DamageMin"}},
	{"Elf", 5, "Green", "Belt", 55, "elf/set/set_elf_s5_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 5, "Green", "Body", 51, "elf/set/set_elf_s5_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Green", "Foots", 54, "elf/set/set_elf_s5_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Green", "Hands", 56, "elf/set/set_elf_s5_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 5, "Green", "Helm", 57, "elf/set/set_elf_s5_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 5, "Green", "Legs", 52, "elf/set/set_elf_s5_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 5, "Green", "Shoulders", 53, "elf/set/set_elf_s5_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 5, "Green", "Weapon", 58, "elf/set/set_elf_s5_green_weapon", []string{"DamageMin"}},
	{"Elf", 5, "Blue", "Belt", 55, "elf/set/set_elf_s5_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 5, "Blue", "Body", 51, "elf/set/set_elf_s5_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Blue", "Foots", 54, "elf/set/set_elf_s5_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Blue", "Hands", 56, "elf/set/set_elf_s5_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 5, "Blue", "Helm", 57, "elf/set/set_elf_s5_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 5, "Blue", "Legs", 52, "elf/set/set_elf_s5_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 5, "Blue", "Shoulders", 53, "elf/set/set_elf_s5_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 5, "Blue", "Weapon", 58, "elf/set/set_elf_s5_grey_weapon", []string{"DamageMin"}},
	{"Elf", 5, "Violet", "Belt", 55, "elf/set/set_elf_s5_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 5, "Violet", "Body", 51, "elf/set/set_elf_s5_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Violet", "Foots", 54, "elf/set/set_elf_s5_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 5, "Violet", "Hands", 56, "elf/set/set_elf_s5_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 5, "Violet", "Helm", 57, "elf/set/set_elf_s5_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 5, "Violet", "Legs", 52, "elf/set/set_elf_s5_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 5, "Violet", "Shoulders", 53, "elf/set/set_elf_s5_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 5, "Violet", "Weapon", 58, "elf/set/set_elf_s5_grey_weapon", []string{"DamageMin"}},
	{"Elf", 6, "Grey", "Belt", 65, "elf/set/set_elf_s6_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 6, "Grey", "Body", 61, "elf/set/set_elf_s6_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Grey", "Foots", 64, "elf/set/set_elf_s6_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Grey", "Hands", 66, "elf/set/set_elf_s6_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 6, "Grey", "Helm", 67, "elf/set/set_elf_s6_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 6, "Grey", "Legs", 62, "elf/set/set_elf_s6_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 6, "Grey", "Shoulders", 63, "elf/set/set_elf_s6_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 6, "Green", "Belt", 65, "elf/set/set_elf_s6_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 6, "Green", "Body", 61, "elf/set/set_elf_s6_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Green", "Foots", 64, "elf/set/set_elf_s6_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Green", "Hands", 66, "elf/set/set_elf_s6_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 6, "Green", "Helm", 67, "elf/set/set_elf_s6_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 6, "Green", "Legs", 62, "elf/set/set_elf_s6_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 6, "Green", "Shoulders", 63, "elf/set/set_elf_s6_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 6, "Blue", "Belt", 65, "elf/set/set_elf_s6_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 6, "Blue", "Body", 61, "elf/set/set_elf_s6_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Blue", "Foots", 64, "elf/set/set_elf_s6_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Blue", "Hands", 66, "elf/set/set_elf_s6_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 6, "Blue", "Helm", 67, "elf/set/set_elf_s6_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 6, "Blue", "Legs", 62, "elf/set/set_elf_s6_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 6, "Blue", "Shoulders", 63, "elf/set/set_elf_s6_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 6, "Violet", "Belt", 65, "elf/set/set_elf_s6_violet_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 6, "Violet", "Body", 61, "elf/set/set_elf_s6_violet_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Violet", "Foots", 64, "elf/set/set_elf_s6_violet_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 6, "Violet", "Hands", 66, "elf/set/set_elf_s6_violet_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 6, "Violet", "Helm", 67, "elf/set/set_elf_s6_violet_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 6, "Violet", "Legs", 62, "elf/set/set_elf_s6_violet_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 6, "Violet", "Shoulders", 63, "elf/set/set_elf_s6_violet_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 7, "Grey", "Belt", 75, "elf/set/set_elf_s7_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 7, "Grey", "Body", 71, "elf/set/set_elf_s7_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Grey", "Foots", 74, "elf/set/set_elf_s7_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Grey", "Hands", 75, "elf/set/set_elf_s7_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 7, "Grey", "Helm", 75, "elf/set/set_elf_s7_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 7, "Grey", "Legs", 72, "elf/set/set_elf_s7_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 7, "Grey", "Shoulders", 73, "elf/set/set_elf_s7_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 7, "Green", "Belt", 75, "elf/set/set_elf_s7_green_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 7, "Green", "Body", 71, "elf/set/set_elf_s7_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Green", "Foots", 74, "elf/set/set_elf_s7_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Green", "Hands", 75, "elf/set/set_elf_s7_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 7, "Green", "Helm", 75, "elf/set/set_elf_s7_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 7, "Green", "Legs", 72, "elf/set/set_elf_s7_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 7, "Green", "Shoulders", 73, "elf/set/set_elf_s7_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 7, "Blue", "Belt", 75, "elf/set/set_elf_s7_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 7, "Blue", "Body", 71, "elf/set/set_elf_s7_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Blue", "Foots", 74, "elf/set/set_elf_s7_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Blue", "Hands", 75, "elf/set/set_elf_s7_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 7, "Blue", "Helm", 75, "elf/set/set_elf_s7_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 7, "Blue", "Legs", 72, "elf/set/set_elf_s7_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 7, "Blue", "Shoulders", 73, "elf/set/set_elf_s7_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Elf", 7, "Violet", "Belt", 75, "elf/set/set_elf_s7_violet_belt", []string{"Mana", "MagicArmor"}},
	{"Elf", 7, "Violet", "Body", 71, "elf/set/set_elf_s7_violet_body", []string{"HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Violet", "Foots", 74, "elf/set/set_elf_s7_violet_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Elf", 7, "Violet", "Hands", 75, "elf/set/set_elf_s7_violet_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Elf", 7, "Violet", "Helm", 75, "elf/set/set_elf_s7_violet_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Elf", 7, "Violet", "Legs", 72, "elf/set/set_elf_s7_violet_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Elf", 7, "Violet", "Shoulders", 73, "elf/set/set_elf_s7_violet_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 0, "Grey", "Body", 1, "human/set/set_human_s0_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 0, "Grey", "Foots", 5, "human/set/set_human_s0_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 0, "Grey", "Hands", 7, "human/set/set_human_s0_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 0, "Grey", "Legs", 1, "human/set/set_human_s0_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 0, "Grey", "Shoulders", 4, "human/set/set_human_s0_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 0, "Grey", "Weapon", 8, "human/set/set_human_s0_grey_weapon", []string{"DamageMin"}},
	{"Human", 1, "Grey", "Belt", 15, "human/set/set_human_s1_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 1, "Grey", "Body", 11, "human/set/set_human_s1_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 1, "Grey", "Foots", 14, "human/set/set_human_s1_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 1, "Grey", "Hands", 16, "human/set/set_human_s1_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 1, "Grey", "Helm", 17, "human/set/set_human_s1_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 1, "Grey", "Legs", 12, "human/set/set_human_s1_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 1, "Grey", "Shoulders", 13, "human/set/set_human_s1_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 1, "Grey", "Weapon", 18, "human/set/set_human_s1_grey_weapon", []string{"DamageMin"}},
	{"Human", 1, "Green", "Belt", 15, "human/set/set_human_s1_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 1, "Green", "Body", 11, "human/set/set_human_s1_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 1, "Green", "Foots", 14, "human/set/set_human_s1_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 1, "Green", "Hands", 16, "human/set/set_human_s1_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 1, "Green", "Helm", 17, "human/set/set_human_s1_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 1, "Green", "Legs", 12, "human/set/set_human_s1_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 1, "Green", "Shoulders", 13, "human/set/set_human_s1_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 1, "Green", "Weapon", 18, "human/set/set_human_s1_green_weapon", []string{"DamageMin"}},
	{"Human", 2, "Grey", "Belt", 25, "human/set/set_human_s2_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 2, "Grey", "Body", 21, "human/set/set_human_s2_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 2, "Grey", "Foots", 24, "human/set/set_human_s2_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 2, "Grey", "Hands", 26, "human/set/set_human_s2_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 2, "Grey", "Helm", 27, "human/set/set_human_s2_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 2, "Grey", "Legs", 22, "human/set/set_human_s2_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 2, "Grey", "Shoulders", 23, "human/set/set_human_s2_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 2, "Grey", "Weapon", 28, "human/set/set_human_s2_grey_weapon", []string{"DamageMin"}},
	{"Human", 2, "Green", "Belt", 25, "human/set/set_human_s2_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 2, "Green", "Body", 21, "human/set/set_human_s2_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 2, "Green", "Foots", 24, "human/set/set_human_s2_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 2, "Green", "Hands", 26, "human/set/set_human_s2_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 2, "Green", "Helm", 27, "human/set/set_human_s2_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 2, "Green", "Legs", 22, "human/set/set_human_s2_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 2, "Green", "Shoulders", 23, "human/set/set_human_s2_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 2, "Green", "Weapon", 28, "human/set/set_human_s2_green_weapon", []string{"DamageMin"}},
	{"Human", 3, "Grey", "Belt", 35, "human/set/set_human_s3_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 3, "Grey", "Body", 31, "human/set/set_human_s3_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 3, "Grey", "Foots", 34, "human/set/set_human_s3_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 3, "Grey", "Hands", 36, "human/set/set_human_s3_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 3, "Grey", "Helm", 37, "human/set/set_human_s3_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 3, "Grey", "Legs", 32, "human/set/set_human_s3_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 3, "Grey", "Shoulders", 33, "human/set/set_human_s3_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 3, "Grey", "Weapon", 38, "human/set/set_human_s3_grey_weapon", []string{"DamageMin"}},
	{"Human", 3, "Green", "Belt", 35, "human/set/set_human_s3_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 3, "Green", "Body", 31, "human/set/set_human_s3_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 3, "Green", "Foots", 34, "human/set/set_human_s3_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 3, "Green", "Hands", 36, "human/set/set_human_s3_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 3, "Green", "Helm", 37, "human/set/set_human_s3_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 3, "Green", "Legs", 32, "human/set/set_human_s3_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 3, "Green", "Shoulders", 33, "human/set/set_human_s3_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 3, "Green", "Weapon", 38, "human/set/set_human_s3_green_weapon", []string{"DamageMin"}},
	{"Human", 3, "Blue", "Belt", 35, "human/set/set_human_s3_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 3, "Blue", "Body", 31, "human/set/set_human_s3_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 3, "Blue", "Foots", 34, "human/set/set_human_s3_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 3, "Blue", "Hands", 36, "human/set/set_human_s3_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 3, "Blue", "Helm", 37, "human/set/set_human_s3_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 3, "Blue", "Legs", 32, "human/set/set_human_s3_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 3, "Blue", "Shoulders", 33, "human/set/set_human_s3_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 3, "Blue", "Weapon", 38, "human/set/set_human_s3_grey_weapon", []string{"DamageMin"}},
	{"Human", 4, "Grey", "Belt", 45, "human/set/set_human_s4_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 4, "Grey", "Body", 41, "human/set/set_human_s4_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 4, "Grey", "Foots", 44, "human/set/set_human_s4_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 4, "Grey", "Hands", 46, "human/set/set_human_s4_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 4, "Grey", "Helm", 47, "human/set/set_human_s4_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 4, "Grey", "Legs", 42, "human/set/set_human_s4_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 4, "Grey", "Shoulders", 43, "human/set/set_human_s4_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 4, "Grey", "Weapon", 48, "human/set/set_human_s4_grey_weapon", []string{"DamageMin"}},
	{"Human", 4, "Green", "Belt", 45, "human/set/set_human_s4_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 4, "Green", "Body", 41, "human/set/set_human_s4_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 4, "Green", "Foots", 44, "human/set/set_human_s4_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 4, "Green", "Hands", 46, "human/set/set_human_s4_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 4, "Green", "Helm", 47, "human/set/set_human_s4_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 4, "Green", "Legs", 42, "human/set/set_human_s4_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 4, "Green", "Shoulders", 43, "human/set/set_human_s4_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 4, "Green", "Weapon", 48, "human/set/set_human_s4_green_weapon", []string{"DamageMin"}},
	{"Human", 4, "Blue", "Belt", 45, "human/set/set_human_s4_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 4, "Blue", "Body", 41, "human/set/set_human_s4_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 4, "Blue", "Foots", 44, "human/set/set_human_s4_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 4, "Blue", "Hands", 46, "human/set/set_human_s4_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 4, "Blue", "Helm", 47, "human/set/set_human_s4_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 4, "Blue", "Legs", 42, "human/set/set_human_s4_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 4, "Blue", "Shoulders", 43, "human/set/set_human_s4_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 4, "Blue", "Weapon", 48, "human/set/set_human_s4_grey_weapon", []string{"DamageMin"}},
	{"Human", 5, "Grey", "Belt", 55, "human/set/set_human_s5_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 5, "Grey", "Body", 51, "human/set/set_human_s5_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 5, "Grey", "Foots", 54, "human/set/set_human_s5_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 5, "Grey", "Hands", 56, "human/set/set_human_s5_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 5, "Grey", "Helm", 57, "human/set/set_human_s5_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 5, "Grey", "Legs", 52, "human/set/set_human_s5_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 5, "Grey", "Shoulders", 53, "human/set/set_human_s5_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 5, "Grey", "Weapon", 58, "human/set/set_human_s5_grey_weapon", []string{"DamageMin"}},
	{"Human", 5, "Green", "Belt", 55, "human/set/set_human_s5_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 5, "Green", "Body", 51, "human/set/set_human_s5_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 5, "Green", "Foots", 54, "human/set/set_human_s5_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 5, "Green", "Hands", 56, "human/set/set_human_s5_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 5, "Green", "Helm", 57, "human/set/set_human_s5_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 5, "Green", "Legs", 52, "human/set/set_human_s5_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 5, "Green", "Shoulders", 53, "human/set/set_human_s5_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 5, "Green", "Weapon", 58, "human/set/set_human_s5_green_weapon", []string{"DamageMin"}},
	{"Human", 5, "Blue", "Belt", 55, "human/set/set_human_s5_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 5, "Blue", "Body", 51, "human/set/set_human_s5_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 5, "Blue", "Foots", 54, "human/set/set_human_s5_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 5, "Blue", "Hands", 56, "human/set/set_human_s5_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 5, "Blue", "Helm", 57, "human/set/set_human_s5_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 5, "Blue", "Legs", 52, "human/set/set_human_s5_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 5, "Blue", "Shoulders", 53, "human/set/set_human_s5_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 5, "Blue", "Weapon", 58, "human/set/set_human_s5_grey_weapon", []string{"DamageMin"}},
	{"Human", 5, "Violet", "Belt", 55, "human/set/set_human_s5_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 5, "Violet", "Body", 51, "human/set/set_human_s5_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 5, "Violet", "Foots", 54, "human/set/set_human_s5_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 5, "Violet", "Hands", 56, "human/set/set_human_s5_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 5, "Violet", "Helm", 57, "human/set/set_human_s5_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 5, "Violet", "Legs", 52, "human/set/set_human_s5_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 5, "Violet", "Shoulders", 53, "human/set/set_human_s5_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 5, "Violet", "Weapon", 58, "human/set/set_human_s5_grey_weapon", []string{"DamageMin"}},
	{"Human", 6, "Grey", "Belt", 65, "human/set/set_human_s6_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 6, "Grey", "Body", 61, "human/set/set_human_s6_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 6, "Grey", "Foots", 64, "human/set/set_human_s6_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 6, "Grey", "Hands", 66, "human/set/set_human_s6_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 6, "Grey", "Helm", 67, "human/set/set_human_s6_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 6, "Grey", "Legs", 62, "human/set/set_human_s6_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 6, "Grey", "Shoulders", 63, "human/set/set_human_s6_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 6, "Green", "Belt", 65, "human/set/set_human_s6_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 6, "Green", "Body", 61, "human/set/set_human_s6_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 6, "Green", "Foots", 64, "human/set/set_human_s6_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 6, "Green", "Hands", 66, "human/set/set_human_s6_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 6, "Green", "Helm", 67, "human/set/set_human_s6_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 6, "Green", "Legs", 62, "human/set/set_human_s6_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 6, "Green", "Shoulders", 63, "human/set/set_human_s6_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 6, "Blue", "Belt", 65, "human/set/set_human_s6_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 6, "Blue", "Body", 61, "human/set/set_human_s6_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 6, "Blue", "Foots", 64, "human/set/set_human_s6_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 6, "Blue", "Hands", 66, "human/set/set_human_s6_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 6, "Blue", "Helm", 67, "human/set/set_human_s6_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 6, "Blue", "Legs", 62, "human/set/set_human_s6_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 6, "Blue", "Shoulders", 63, "human/set/set_human_s6_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 6, "Violet", "Belt", 65, "human/set/set_human_s6_violet_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 6, "Violet", "Body", 61, "human/set/set_human_s6_violet_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 6, "Violet", "Foots", 64, "human/set/set_human_s6_violet_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 6, "Violet", "Hands", 66, "human/set/set_human_s6_violet_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 6, "Violet", "Helm", 67, "human/set/set_human_s6_violet_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 6, "Violet", "Legs", 62, "human/set/set_human_s6_violet_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 6, "Violet", "Shoulders", 63, "human/set/set_human_s6_violet_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 7, "Grey", "Belt", 75, "human/set/set_human_s7_grey_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 7, "Grey", "Body", 71, "human/set/set_human_s7_grey_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 7, "Grey", "Foots", 74, "human/set/set_human_s7_grey_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 7, "Grey", "Hands", 75, "human/set/set_human_s7_grey_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 7, "Grey", "Helm", 75, "human/set/set_human_s7_grey_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 7, "Grey", "Legs", 72, "human/set/set_human_s7_grey_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 7, "Grey", "Shoulders", 73, "human/set/set_human_s7_grey_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 7, "Green", "Belt", 75, "human/set/set_human_s7_green_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 7, "Green", "Body", 71, "human/set/set_human_s7_green_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 7, "Green", "Foots", 74, "human/set/set_human_s7_green_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 7, "Green", "Hands", 75, "human/set/set_human_s7_green_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 7, "Green", "Helm", 75, "human/set/set_human_s7_green_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 7, "Green", "Legs", 72, "human/set/set_human_s7_green_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 7, "Green", "Shoulders", 73, "human/set/set_human_s7_green_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 7, "Blue", "Belt", 75, "human/set/set_human_s7_blue_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 7, "Blue", "Body", 71, "human/set/set_human_s7_blue_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 7, "Blue", "Foots", 74, "human/set/set_human_s7_blue_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 7, "Blue", "Hands", 75, "human/set/set_human_s7_blue_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 7, "Blue", "Helm", 75, "human/set/set_human_s7_blue_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 7, "Blue", "Legs", 72, "human/set/set_human_s7_blue_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 7, "Blue", "Shoulders", 73, "human/set/set_human_s7_blue_shoulders", []string{"Health", "MagicArmor"}},
	{"Human", 7, "Violet", "Belt", 75, "human/set/set_human_s7_violet_belt", []string{"Mana", "MagicArmor"}},
	{"Human", 7, "Violet", "Body", 71, "human/set/set_human_s7_violet_body", []string{"HealthRegen", "PhysArmor"}},
	{"Human", 7, "Violet", "Foots", 74, "human/set/set_human_s7_violet_foots", []string{"Health", "HealthRegen", "PhysArmor"}},
	{"Human", 7, "Violet", "Hands", 75, "human/set/set_human_s7_violet_hands", []string{"Health", "AttackSpeed", "CritChance"}},
	{"Human", 7, "Violet", "Helm", 75, "human/set/set_human_s7_violet_helm", []string{"Mana", "ManaRegen", "AntiMagicArmor"}},
	{"Human", 7, "Violet", "Legs", 72, "human/set/set_human_s7_violet_legs", []string{"Mana", "ManaRegen", "AntiPhysArmor"}},
	{"Human", 7, "Violet", "Shoulders", 73, "human/set/set_human_s7_violet_shoulders", []string{"Health", "MagicArmor"}},
}
